FROM node:12

WORKDIR /usr/src/app

COPY package.json package-lock.json /usr/src/app/
COPY integration /usr/src/app/integration/
RUN npm install

COPY . .
RUN npm run build

EXPOSE 3000
ENV PORT 3000

CMD [ "npm", "run", "start:dev" ]
